//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectsAccounting.DAL.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectsAccountingEntities : DbContext
    {
        public ProjectsAccountingEntities()
            : base("name=ProjectsAccountingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProjectRates> ProjectRates { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<InvoicedTasks> InvoicedTasks { get; set; }
        public virtual DbSet<CompanyInfo> CompanyInfo { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<Invoices> Invoices { get; set; }
    }
}
