//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectsAccounting.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInfo
    {
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string MainAccpuntantName { get; set; }
        public string OwnerName { get; set; }
        public string LocationAddress { get; set; }
        public string Fax { get; set; }
        public string Phone { get; set; }
        public Nullable<double> TaxRate { get; set; }
        public Nullable<double> OfficeRate { get; set; }
    }
}
