//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectsAccounting.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectRates
    {
        public int ProjectRateId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<double> ExternalRate { get; set; }
    
        public virtual Projects Projects { get; set; }
        public virtual Users Users { get; set; }
    }
}
