//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectsAccounting.TFS.TFSDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADObjects
    {
        public int PartitionId { get; set; }
        public string DomainName { get; set; }
        public string SamAccountName { get; set; }
        public string MailNickName { get; set; }
        public byte ObjectCategory { get; set; }
        public byte ObjectSpecialType { get; set; }
        public System.DateTime LastSyncUTC { get; set; }
        public bool fDeleted { get; set; }
        public string ObjectSID { get; set; }
        public string DisplayName { get; set; }
        public int SeqId { get; set; }
        public System.Guid TeamFoundationId { get; set; }
        public Nullable<bool> ForceProcess { get; set; }
    }
}
