//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectsAccounting.TFS.TFSDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADObjectMemberships
    {
        public int PartitionId { get; set; }
        public string ObjectSID { get; set; }
        public string MemberObjectSID { get; set; }
    }
}
