//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectsAccounting.TFS.TFSDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Iteration
    {
        public int PartitionId { get; set; }
        public int IterationId { get; set; }
        public string IterationUri { get; set; }
        public string Iteration { get; set; }
        public string ProjectUri { get; set; }
        public int DataspaceId { get; set; }
        public Nullable<int> SequenceId { get; set; }
    }
}
