//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectsAccounting.TFS.TFSDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tfs_DefaultCollectionEntities : DbContext
    {
        public Tfs_DefaultCollectionEntities()
            : base("name=Tfs_DefaultCollectionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_Project> tbl_Project { get; set; }
        public DbSet<ADObjectMemberships> ADObjectMemberships { get; set; }
        public DbSet<ADObjects> ADObjects { get; set; }
        public DbSet<tbl_Iteration> tbl_Iteration { get; set; }
        public DbSet<WorkItemLongTexts> WorkItemLongTexts { get; set; }
        public DbSet<vw_denorm_WorkItemCoreLatest> vw_denorm_WorkItemCoreLatest { get; set; }
    }
}
