//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectsAccounting.TFS.TFSDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_denorm_WorkItemCoreLatest
    {
        public int System_Id { get; set; }
        public int System_Rev { get; set; }
        public System.DateTime System_AuthorizedDate { get; set; }
        public System.DateTime System_RevisedDate { get; set; }
        public string System_WorkItemType { get; set; }
        public System.DateTime System_CreatedDate { get; set; }
        public System.DateTime System_ChangedDate { get; set; }
        public string System_State { get; set; }
        public string System_Reason { get; set; }
        public int System_PersonId { get; set; }
        public int System_Watermark { get; set; }
        public Nullable<int> System_AreaId { get; set; }
        public Nullable<int> System_IterationId { get; set; }
        public bool System_IsDeleted { get; set; }
        public string System_TeamProject { get; set; }
        public string System_NodeName { get; set; }
        public string System_IterationLevel7 { get; set; }
        public string System_IterationLevel6 { get; set; }
        public string System_IterationLevel5 { get; set; }
        public string System_IterationLevel4 { get; set; }
        public string System_IterationLevel3 { get; set; }
        public string System_IterationLevel2 { get; set; }
        public string System_IterationLevel1 { get; set; }
        public string System_AreaLevel7 { get; set; }
        public string System_AreaLevel6 { get; set; }
        public string System_AreaLevel5 { get; set; }
        public string System_AreaLevel4 { get; set; }
        public string System_AreaLevel3 { get; set; }
        public string System_AreaLevel2 { get; set; }
        public string System_AreaLevel1 { get; set; }
        public string System_AreaPath { get; set; }
        public string System_IterationPath { get; set; }
        public int System_AttachedFileCount { get; set; }
        public int System_HyperlinkCount { get; set; }
        public int System_ExternalLinkCount { get; set; }
        public int System_RelatedLinkCount { get; set; }
        public string System_AssignedTo { get; set; }
        public Nullable<System.Guid> System_AssignedTo_TeamFoundationId { get; set; }
        public Nullable<int> System_AssignedTo_ConstId { get; set; }
        public string System_CreatedBy { get; set; }
        public Nullable<System.Guid> System_CreatedBy_TeamFoundationId { get; set; }
        public Nullable<int> System_CreatedBy_ConstId { get; set; }
        public string System_ChangedBy { get; set; }
        public Nullable<System.Guid> System_ChangedBy_TeamFoundationId { get; set; }
        public Nullable<int> System_ChangedBy_ConstId { get; set; }
        public string System_AuthorizedAs { get; set; }
        public Nullable<System.Guid> System_AuthorizedAs_TeamFoundationId { get; set; }
        public Nullable<int> System_AuthorizedAs_ConstId { get; set; }
        public int PartitionId { get; set; }
        public int DataspaceId { get; set; }
        public int Id { get; set; }
        public int Rev { get; set; }
        public System.DateTime AuthorizedDate { get; set; }
        public System.DateTime RevisedDate { get; set; }
        public int AuthorizedAs { get; set; }
        public string WorkItemType { get; set; }
        public byte[] AreaPath { get; set; }
        public Nullable<int> AreaId { get; set; }
        public byte[] IterationPath { get; set; }
        public Nullable<int> IterationId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ChangedBy { get; set; }
        public System.DateTime ChangedDate { get; set; }
        public string State { get; set; }
        public string Reason { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public int Watermark { get; set; }
        public bool IsDeleted { get; set; }
    }
}
