//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectsAccounting.TFS.TFSDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkItemLongTexts
    {
        public int PartitionId { get; set; }
        public int DataspaceId { get; set; }
        public System.DateTime AddedDate { get; set; }
        public int FldID { get; set; }
        public int ID { get; set; }
        public string Words { get; set; }
        public byte[] Changed_Order { get; set; }
        public int Rev { get; set; }
        public bool fHtml { get; set; }
        public byte[] IndexedWords { get; set; }
        public string WordsDocumentType { get; set; }
        public int TextID { get; set; }
        public System.DateTime EndDate { get; set; }
        public long PartitionTextID { get; set; }
    }
}
